leftnav:
- identifier: 7ad701da-fb21-4ee4-f174-141e670cab04
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0fd1b9d4-ade6-8890-9f59-8df0891241d7
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 20
- identifier: db02fb8f-2784-8eb9-d53c-72fe22be0540
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: a70e36d3-e6db-5a0d-fcf5-2fbacf3f865c
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 97836880-c1a7-546a-28e3-e4c6fc0f92dc
  name: Download Course Materials
  pageRef: /pages/download-course-materials
  weight: 50
